#!/bin/bash


function create_flavors(){(
    set -xv
    openstack flavor create --vcpus 1 --ram 1024 --disk 2 small
    openstack flavor create --vcpus 2 --ram 2048 --disk 4 medium
    openstack flavor create --vcpus 4 --ram 4086 --disk 8 large
)}

function create_image_cirros(){(
    [ -f cirros-0.6.2-x86_64-disk.img ] || wget https://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img
    set -xv
    openstack image create \
     --file cirros-0.6.2-x86_64-disk.img \
     --container-format bare \
     --disk-format qcow2 \
     --property hw_disk_bus=scsi \
     --property hw_scsi_model=virtio-scsi \
     --property os_type=linux \
     --property os_distro=cirros \
     --property os_admin_user=cirros \
     --property os_version='0.6.2' \
     --public \
     "cirros"
)}

function create_image_debian(){(
    [ -f debian-12-genericcloud-amd64.qcow2 ] || wget https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2
    set -xv
    openstack image create \
     --file debian-12-genericcloud-amd64.qcow2 \
     --container-format bare \
     --disk-format qcow2 \
     --property hw_disk_bus=scsi \
     --property hw_scsi_model=virtio-scsi \
     --property os_type=linux \
     --property os_distro=debian \
     --property os_admin_user=debian \
     --property os_version='12.0.0' \
     --public \
     "Debian 12"
)}

function create_key(){(
    set -xv
    openstack keypair create --public-key ~/.ssh/authorized_keys zob
)}

function create_rules(){(
    set -xv
    openstack security group rule create --ingress --protocol any default
    # Already supposed to exist
    #openstack security group rule create --egress  --protocol any default
)}

function create_server_private(){(
    set -xv
    openstack server create \
     --flavor small \
     --image cirros \
     --net private \
     --key-name zob \
     n1
)}

function create_server_public(){(
    set -xv
    openstack server create \
     --flavor small \
     --image cirros \
      --net public \
      --key-name zob \
     p1
)}

function create_floating(){(
    set -xv
    openstack floating ip create public
)}

function attach_floating(){(
    NAME=$1
    IP=$2
    set -xv
    openstack server add floating ip $NAME $IP
)}

function create_network_public(){(
    START=$1
    END=$2
    if [[ $START == 51.91.90.* ]] ; then
        # This is the only /25 that I currently have
        # So I can hardcode the values here
        RANGE="51.91.90.0/25"
        GATEWAY="51.91.90.126"
    else
        # Try to compute from START
        RANGE=$(ipcalc -n -b ${START}/28 | grep 'Network:' | awk '{print $2}')
        GATEWAY=$(ipcalc -n -b ${START}/28 | grep 'HostMax:' | awk '{print $2}')
    fi

    set -xv
    openstack network create \
     --share \
     --external \
     --provider-physical-network provider \
     --provider-network-type flat \
     public

    openstack subnet create \
     --network public \
     --subnet-range "$RANGE" \
     --allocation-pool "start=${START},end=${END}" \
     --gateway $GATEWAY \
     --dns-nameserver 1.1.1.1 \
     "$RANGE"

    # Add a private subnet in this public network
    # The service-type network:floatingip_agent_gateway
    # will let IPAM give IP from this subnet for FIP namespaces
    # This is used to reduce number of public IP on neutron DVR
    # Note that we still need to set a valid next-hop gateway
    # ($GATEWAY here)
    openstack subnet create \
     --network public \
     --subnet-range 172.31.0.0/17 \
     --gateway $GATEWAY \
     --no-dhcp \
     --service-type 'network:floatingip_agent_gateway' \
     _internal_fip_subnet
)}

function create_network_private(){(
    set -xv
    openstack network create private
    openstack subnet create \
     --network private \
     --subnet-range "192.168.42.0/24" \
     --gateway 192.168.42.1 \
     --dns-nameserver 8.8.8.8 \
     "192.168.42.0/24"
)}

function create_router(){(
    set -xv
    openstack router create router
    openstack router set --external-gateway public router
    openstack router add subnet router 192.168.42.0/24
)}
