#!/bin/bash

# Setup logging stdout + stderr to logfile
log_file="/var/log/postinstall.log"

function log_handler {
  while IFS='' read -r output; do
    echo $output
    echo "$(date) - $output" >> $log_file
  done
}

exec &> >(log_handler)

# Note: this is not very secure to use this key because:
# - it is on github without any protection
# - it does not have any password
cat <<EOF >/root/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDY15cdBmIs2XOpe4EiFCsaY6bmUmK/GysMoLl4UG51JCfJwvwoWCoA+6mDIbymZxhxq9IGxilp/yTA6WQ9s/5pBag1cUMJmFuda9PjOkXl04jgqh5tR6I+GZ97AvCg93KAECis5ubSqw1xOCj4utfEUtPoF1OuzqM/lE5mY4N6VKXn+fT7pCD6cifBEs6JHhVNvs5OLLp/tO8Pa3kKYQOdyS0xc3rh+t2lrzvKUSWGZbX+dLiFiEpjsUL3tDqzkEMNUn4pdv69OJuzWHCxRWPfdrY9Wg0j3mJesP29EBht+w+EC9/kBKq+1VKdmsXUXAcjEvjovVL8l1BrX3BY0R8D zob
EOF

# Update apt cache
apt-get update

apt-get -y install tmux curl vim wget ipcalc mosh git ansible

# Disable vim mouse support -- this is insupportable
cat <<'EOF' > /etc/vim/vimrc.local
set mouse=
set ttymouse=
EOF

# Install tmux config
curl --output /root/.tmux.conf https://www.arnaudmorin.fr/tmux.conf

# Install plik
curl --output /usr/local/bin/plik https://plik.arno.ovh/clients/linux-amd64/plik
chmod +x /usr/local/bin/plik
cat <<'EOF' > /root/.plikrc
Url = "https://plik.arno.ovh"
EOF

# Install stern
wget -qO- https://github.com/stern/stern/releases/download/v1.22.0/stern_1.22.0_linux_amd64.tar.gz | tar xvz -C /usr/local/bin/ stern
chmod +x /usr/local/bin/stern
echo 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' > /etc/profile.d/stern.sh

# Update apt cache
apt-get update

# Add useful aliases - not useful everywhere but at least we have them
echo 'alias k=kubectl' > /etc/profile.d/aliases.sh
echo 'alias l=stern' >> /etc/profile.d/aliases.sh
echo 'alias os=openstack' >> /etc/profile.d/aliases.sh
echo 'export EDITOR=vim' >> /etc/profile.d/editor.sh

apt-get -y purge cloud-init

echo 'done'
