#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This script create ressource on target keystone from a config file
"""
# Lint : pylint ovh-create-keystone-resources.py -d W1203,E1120,W0621,C0201,R0902,C0103,E0401,W0703,C0301
import argparse
import configparser
import logging
from threading import Lock
from multiprocessing import Pool, cpu_count
from sys import exit as sexit


from yaml import safe_load as yaml_safe_load
from urllib3 import disable_warnings
from keystoneclient import session, utils, exceptions
from keystoneclient.auth import identity
from keystoneclient.v3 import client

# Tool for dev not required on prod
try:
    from rich.traceback import install
    install(show_locals=True)
except ImportError:
    pass

# POOL_PROCESSES = cpu_count() * 2
POOL_PROCESSES = 2
OPENSTACK_INTERCES = ['admin', 'public', 'internal']
LOG = logging.getLogger(__name__)
logging.getLogger("requests.packages.urllib3.connectionpool").setLevel(logging.WARNING)
logging.basicConfig(level=logging.ERROR, format='[%(levelname)8s] %(message)s')
disable_warnings()


def chunkify(lst: list, n: int, remove_empty=True):
    """Convert a list into a n sublist repartited equaly"""
    result = [lst[i::n] for i in range(n)]
    if remove_empty:
        return [item for item in result if len(item) > 0]
    return result

class SingletonMeta(type):
    """
    This is a thread-safe implementation of Singleton.
    """

    _instances = {}
    _lock: Lock = Lock()

    def __call__(cls, *args, **kwargs):
        with cls._lock:
            if cls not in cls._instances:
                instance = super().__call__(*args, **kwargs)
                cls._instances[cls] = instance
        return cls._instances[cls]

class KeyStoneFeed(metaclass=SingletonMeta):
    """
    Object wuth *_map to avoid making to mutch useless call
    Store creds from config to init keystone client
    """

    # value from keystone_settings
    openstack_region_name: str
    openstack_endpoints: dict
    openstack_users_roles: dict

    # openstack auth
    auth_url: str
    username: str
    password: str
    project_name: str
    user_domain_name: str
    project_domain_name: str

    # running map
    keystone_endpoint_map: list # endpoint object (enabled,id,interface,links,region,region_id, service_id
    keystone_services_map: dict # {service_name:id}
    keystone_domains_map: dict # {domain_name:id}
    keystone_roles_map: dict # {role_name:id}
    keystone_projects_map: dict # {domain:{project_name:id}}
    keystone_users_map: dict # {domain:{user_name:id}}

    def __init__(self, args: dict):
        config = configparser.ConfigParser()
        config.read(args.conf)
        self.auth_url=config.get('admin_credentials', 'endpoint')
        self.username=config.get('admin_credentials', 'username')
        self.password=config.get('admin_credentials', 'password')
        self.project_name = config.get('admin_credentials', 'project_name')
        self.user_domain_name=config.get('admin_credentials', 'user_domain_name')
        self.project_domain_name=config.get('admin_credentials', 'project_domain_name')

        with open(args.keystone_conf, 'r', encoding="UTF-8") as stream:
            keystone_settings = yaml_safe_load(stream.read())
            self.openstack_region_name = keystone_settings['region']
            self.openstack_endpoints = keystone_settings['endpoints']
            self.openstack_users_roles = keystone_settings['users_roles']

        LOG.info("Refreshing map")
        LOG.info("1/6 Update services map")
        self.refresh_keystone_services_map()
        LOG.info("2/6 Update endpoints map")
        self.refresh_keystone_endpoints_map()
        LOG.info("3/6 Update projects map")
        self.refresh_keystone_project_map()
        LOG.info("4/6 Update roles map")
        self.refresh_keystone_roles_map()
        LOG.info("5/6 Update users map")
        self.refresh_keystone_users_map()
        LOG.info("6/6 Update domains map")
        self.validate_domain()
        LOG.info("Done")

    #
    # Extract and convert data from config file
    #

    def _get_users_flaten(self):
        """
        Convert nested dict users_roles into a list of dict with all info
        {
            "domain": ""
            "project: ""
            "user": ""
            "roles": []
            "password": ""
        }
        Used for domain validation and user, project, role creation / bindings
        """
        result = []
        for domain_name, projects_dict in self.openstack_users_roles.items():
            for project_name, users_dict in projects_dict.items():
                for user_name, value in users_dict.items():
                    result.append({
                        "domain": domain_name,
                        "project": project_name,
                        "user": user_name,
                        "roles": value.get("roles", []),
                        "password": value.get("password", "")
                    })
        return result

    def get_config_domain(self):
        """Return list of domain in settings"""
        return {item.get("domain") for item in self._get_users_flaten()}

    def get_keystone_client(self):
        """
        Init or reinit the self.keystone_client
        """
        auth = identity.v3.Password(
            auth_url=self.auth_url,
            username=self.username,
            password=self.password,
            project_name = self.project_name,
            user_domain_name=self.user_domain_name,
            project_domain_name=self.project_domain_name
        )
        sess = session.Session(auth=auth, timeout=20, verify=False)
        return client.Client(session=sess, connect_retries=10)

    #
    # Create name/id map to avoid making useless call to keystone
    #

    def refresh_keystone_services_map(self):
        """
        Refresh dict of struct svc_name / svc_id
        """
        self.keystone_services_map = {
            service.name: service.id
            for service in self.get_keystone_client().services.list()
        }

    def refresh_keystone_endpoints_map(self):
        """Refresh list of endpoint"""
        self.keystone_endpoint_map = list(self.get_keystone_client().endpoints.list())

    def refresh_keystone_roles_map(self):
        """
        Refresh dict of struct role_name / role_id
        """
        roles = {
            role.name: role.id
            for role in self.get_keystone_client().roles.list()
        }
        self.keystone_roles_map = roles

    def refresh_keystone_project_map(self):
        """
        Refresh a nested dict {domain:{project_name:id}}
        use full to get id of a project in a domain without calling api
        """
        base = {}
        for project in self.get_keystone_client().projects.list(region=self.openstack_region_name):
            if project.domain_id not in base.keys():
                base[project.domain_id] = {}
            base[project.domain_id][project.name] = project.id
        self.keystone_projects_map = base

    def refresh_keystone_users_map(self):
        """
        Refresh a nested dict {domain:{user_name:id}}
        use full to get id of a user in a domain without calling api
        """
        base = {}
        for user in self.get_keystone_client().users.list():
            if user.domain_id not in base.keys():
                base[user.domain_id] = {}
            base[user.domain_id][user.name] = user.id
        self.keystone_users_map = base

    #
    # Create keystone ressource
    #

    def create_services(self):
        """
        Create missing service type on keystone
        """
        LOG.info("Running services creation")
        early_present = list(self.keystone_services_map.keys())
        service_to_create = []
        for service_name in self.openstack_endpoints.keys():
            service_type = self.openstack_endpoints[service_name]['service_type']
            if service_name in early_present:
                LOG.debug(f"Service {service_name} of type {service_type} early present on target")
                continue
            early_present.append(service_name)
            service_to_create.append(service_name + "|" + service_type)
        todo = chunkify(service_to_create, POOL_PROCESSES)
        toto_len = len(todo)
        if toto_len > 0:
            with Pool(processes=toto_len) as pool:
                pool.map(_pool_create_services, todo)
        self.refresh_keystone_services_map()

    def create_endpoints(self):
        """
        Create and update all endpoint on keystone
        """
        LOG.info("Running endpoints creation")
        todo = chunkify(list(self.openstack_endpoints.keys()), POOL_PROCESSES)
        toto_len = len(todo)
        if toto_len > 0:
            with Pool(processes=toto_len) as pool:
                pool.map(_pool_create_endpoints, todo)
        self.refresh_keystone_endpoints_map()

    def validate_domain(self):
        """
        Check if all domains in settings exist on keystone crash if not present
        Note: cf old code for why wee crash and dont create it
        """
        LOG.info("Checking if domains exists")
        keystone_client = self.get_keystone_client()
        keystone_domains_map = {}
        todo = {item.get("domain") for item in self._get_users_flaten()}
        for domain_name in todo:
            try:
                domain = utils.find_resource(keystone_client.domains, domain_name)
                keystone_domains_map[domain_name] = domain.id
                LOG.info(f'Domain {domain_name} exist')
            except exceptions.CommandError:
                LOG.error(f"Unable to find domain={domain_name}")
                sexit(-1)
        self.keystone_domains_map = keystone_domains_map

    def create_projects(self):
        """Create all missing project"""
        LOG.info("Running projects creation")
        keystone_client = self.get_keystone_client()
        for domain in self.get_config_domain():
            project_in_keystone = set(self.keystone_projects_map[domain].keys())
            project_in_config = {item.get("project") for item in self._get_users_flaten() if item.get("domain") == domain}
            project_to_create = project_in_config - project_in_keystone
            for project in project_to_create:
                LOG.info(f"Create Project {project} on domain {domain}")
                keystone_client.projects.create(name=project, domain=domain, enabled=True) # TODO move this part to a pool
        self.refresh_keystone_project_map()

    def create_users(self):
        """Run a pool to create or update all user required"""
        LOG.info("Running users creation")
        todo = chunkify(self._get_users_flaten(), POOL_PROCESSES)
        toto_len = len(todo)
        if toto_len > 0:
            with Pool(processes=toto_len) as pool:
                pool.map(_pool_create_users, todo)
        self.refresh_keystone_users_map()

    def create_roles(self):
        """
        Create openstack roles
        """
        LOG.info("Running roles creations")
        keystone_client = self.get_keystone_client()

        roles_map = self.keystone_roles_map
        roles_map_keys = roles_map.keys()
        for user in self._get_users_flaten():
            for role in user.get("roles"):
                if role not in roles_map_keys:
                    LOG.info(f"Create role {role}")
                    os_role = keystone_client.roles.create(role) # TODO move this part to a pool
                    roles_map[os_role.name] = os_role.id
                    continue
                LOG.debug(f"Role {role} early exists")
        self.keystone_roles_map = roles_map

    def apply_permissions(self):
        """
        Add user in group and grand role on project
        """
        # contain 3 key with id to create role bind
        # project, user, role
        LOG.info("Running apply role to user on project")
        grants = []

        # TODO add grant map to avoid trying to regrant permissions

        # build list with all information
        for user in self._get_users_flaten():
            os_domain_id = self.keystone_domains_map.get(user.get("domain"))
            os_project_id = self.keystone_projects_map.get(os_domain_id).get(user.get("project"))
            os_user_id = self.keystone_users_map.get(os_domain_id).get(user.get("user"))
            for role in user.get("roles"):
                os_role_id = self.keystone_roles_map.get(role)
                if not os_domain_id or not os_project_id or not os_user_id or not os_role_id:
                    LOG.warning(f"Missing information to create role {role} for user {user}: cant get openstack ID")
                    continue
                grants.append({
                    "role_name": role,
                    "role_id": os_role_id,
                    "user_name": user.get("user"),
                    "user_id": os_user_id,
                    "project_id": os_project_id,
                    "project_name": user.get("project")
                })

        todo = chunkify(grants, POOL_PROCESSES)
        toto_len = len(todo)
        if toto_len > 0:
            with Pool(processes=toto_len) as pool:
                pool.map(_pool_apply_permissions, todo)

    def associate_endpoints(self):
        """Build a map of project_id/endpoint_id to create link"""
        LOG.info("Running associate endpoint to project")
        ass_map = []
        for _, domain_id in self.keystone_domains_map.items():
            for _, project_id in self.keystone_projects_map.get(domain_id).items():
                for endpoint in self.keystone_endpoint_map:
                    ass_map.append(project_id + "|" + endpoint.id)

        todo = chunkify(ass_map, POOL_PROCESSES)
        toto_len = len(todo)
        if toto_len > 0:
            with Pool(processes=toto_len) as pool:
                pool.map(_pool_associate_endpoints, todo)

def _pool_associate_endpoints(lst: list):
    ksf = KeyStoneFeed()
    keystone_client = ksf.get_keystone_client()
    for item in lst:
        project, endpoint = item.split("|")

        endpoint_id_list = [endpoint.id for endpoint in keystone_client.endpoint_filter.list_endpoints_for_project(project)]

        if endpoint not in endpoint_id_list:
            LOG.info(f"Associate project {project} to endpoint {endpoint}")
            keystone_client.endpoint_filter.add_endpoint_to_project(project=project, endpoint=endpoint)

def _pool_create_services(lst: list):
    keystone_driver = KeyStoneFeed().get_keystone_client()
    for item in lst:
        service_name, service_type = item.split("|")
        LOG.info(f"Create service {service_name} of type {service_type}")
        keystone_driver.services.create(service_name, type=service_type)

def _pool_apply_permissions(lst: list):
    ksf =  KeyStoneFeed()
    keystone_client = ksf.get_keystone_client()
    for item in lst:
        keystone_client.roles.grant(
            role=item.get("role_id"),
            user=item.get("user_id"),
            project=item.get("project_id")
        )
        LOG.info(f"Created / Updated grand for user {item.get('user_name')} with role {item.get('role_name')} for project {item.get('project_name')}")

def _pool_create_users(lst: list):

    ksf = KeyStoneFeed()
    keystone_client = ksf.get_keystone_client()

    for user in lst: # add chunkify here to setup pooling
        domain_name = user.get("domain")
        try:
            openstack_user = utils.find_resource(keystone_client.users, user.get("user"))
        except Exception:
            LOG.info(f"Create user{user.get('user')} password on domain={domain_name}")
            keystone_client.users.create(user.get("user"), domain=ksf.keystone_domains_map[domain_name], password=user.get("password"))
        else:
            LOG.info(f"Update user{user.get('user')} password on domain={domain_name}")
            keystone_client.users.update(openstack_user, domain=ksf.keystone_domains_map[domain_name], password=user.get("password"))

def _pool_create_endpoints(lst: list):
    ksf = KeyStoneFeed()
    keystone_driver = ksf.get_keystone_client()
    service_type_map = ksf.keystone_services_map

    for service_name in lst:
        service_endpoints = ksf.openstack_endpoints[service_name]['endpoints']
        for interface in ['admin', 'public', 'internal']:

            service_id = service_type_map[service_name]

            # extract endpoint url
            endpoint_url = None
            if isinstance(service_endpoints, dict):
                endpoint_url = service_endpoints.get(interface)
            else:
                endpoint_url = service_endpoints
            if not endpoint_url:
                continue

            # extract endpoint if exist
            openstack_endpoint = keystone_driver.endpoints.list(service=service_id, interface=interface, region=ksf.openstack_region_name)
            openstack_endpoint = next(iter(openstack_endpoint), None)

            # Create / Update
            if not openstack_endpoint:
                LOG.info(f"Create endpoint region={ksf.openstack_region_name}, service={service_id}, interface={interface}, url={endpoint_url}")
                keystone_driver.endpoints.create(region=ksf.openstack_region_name, service=service_id, interface=interface, url=endpoint_url)
                continue
            LOG.info(f"Update endpoint region={ksf.openstack_region_name}, service={service_id}, interface={interface}, url={endpoint_url}")
            keystone_driver.endpoints.update(openstack_endpoint, service=service_id, url=endpoint_url, interface=interface, region=ksf.openstack_region_name)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('--conf', help='Keystone admin credentials',
                        metavar='/etc/ovh.conf.d/keystone_auth.conf',
                        default='/etc/ovh.conf.d/keystone_auth.conf')
    parser.add_argument('--keystone_conf', help='Keystone settings endpoint/users',
                        metavar='/etc/ovh.conf.d/keystone_settings.yaml',
                        default='/etc/ovh.conf.d/keystone_settings.yaml')
    parser.add_argument('--log', help='log level to display',
                        choices=['error', 'info', 'debug'], default='info')
    parser.add_argument('--debug', action='store_true', help='trigger debug mode')

    args = parser.parse_args()

    if args.log:
        level = logging.getLevelName(args.log.upper())
        logging.getLogger().setLevel(level)
    if args.debug:
        logging.getLogger().setLevel(logging.DEBUG)

    ksf = KeyStoneFeed(args=args)
    ksf.create_services()
    ksf.create_endpoints()
    ksf.validate_domain()
    ksf.create_projects()
    ksf.create_users()
    ksf.create_roles()
    ksf.apply_permissions()
    ksf.associate_endpoints()
